// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"context"
	"github.com/suzuki-shunsuke/discussion-slack-notifier/pkg/config"
	"github.com/suzuki-shunsuke/discussion-slack-notifier/pkg/entry-filter"
	"github.com/suzuki-shunsuke/discussion-slack-notifier/pkg/input"
)

// Injectors from wire.go:

func InitializeController(ctx context.Context, param *input.Param) *Controller {
	gitHub := newGitHub(ctx, param)
	slack := newSlack(param)
	reader := config.NewReader()
	controllerPayloadReader := newPayloadReader()
	filterFilter := filter.New()
	controller := New(gitHub, slack, reader, controllerPayloadReader, filterFilter)
	return controller
}
